//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public Nullable<int> owner_id { get; set; }
        public string description { get; set; }
        public Nullable<int> worker_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> flat_id { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> type_id { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual Type Type { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
